### ISSUE TITLE
[Android] hangs on old Samsungs since 1.5.39

### ISSUE THREAD

**Issue by eugene-s-nesdev** [Rakashazi/emu-ex-plus-alpha#166] opened 2020-05-25 20:00 UTC
I've did global tests on different hardware, and found that
all "xxx.emu" emulators hangs on old Samsungs since 1.5.39 version. 
Current 1.5.43 affected too.

Tested on:
- Galaxy S2 [GT-i9100] (Android 4.1.2) 
- Galaxy Tab 7 Plus [GT-P6200] (Android 4.1.2)
- Galaxy Note 3 [SM-N900] (Android 5.0)

Step by step:
- run emulator, you can run game too, but it not necessary
- turn off dispaly by quick pressing power button (it will "pause" emulator)
- wait about 1-2 minutes (important step!)
- turn on display again by pressing power button
Result = absolutely hang-on, need to kill process or reboot device.

Also tested on:
- Xiaomi Mi 9T Pro (Android 10) - all works correctly

I know Galaxy S2, Note 3 etc. is very obsolete, but maybe this info will be interesting.

**Comment by Rakashazi** [comment] 2020-05-29 02:32
Thanks for the report, out of those devices I have the Galaxy S2 but it's running CyanogenMod based on Android 4.3.1 and wasn't able to reproduce the issue on it. Can you try the test APK below and post the logcat starting from when you launch the app until it hangs?

https://drive.google.com/file/d/1rWKCXhdfZkPnQe2G4TK8A8PzI6fyqdRy/view

**Comment by eugene-s-nesdev** [comment] 2020-05-29 08:47
[debug_ver_sgs2_1_of_1_time_crash.txt](https://github.com/Rakashazi/emu-ex-plus-alpha/files/4700664/debug_ver_sgs2_1_of_1_time_crash.txt)

**Comment by Rakashazi** [comment] 2020-05-31 19:56
Thanks for the additional info over email. It looks like the system was waking up all worker threads unexpectedly while in the background, causing them to exit. I've updated all the event loop code to test a condition so it only exits the thread when requested by the app. The fix will be included in the upcoming 1.5.44 update.

**Closed by Rakashazi** 2020-05-31 19:56 UTC
