### ISSUE TITLE
UI can't respond to mouse clicks properly.

### ISSUE THREAD

**Issue by RebelliousX** [Rakashazi/emu-ex-plus-alpha#250] opened 2021-12-29 07:58 UTC
Not really a bug but more of an annoyance, the user interface works well with gamepads.
But when I use a mouse to navigate the list of menu items of the Emu, I can only select
and highlight the menu item and it won't show anything else.
Using Android TV like Shield TV with a mouse.

For example, I can click on Options, the Options menu get highlighted, but won't go inside
it to show me options. Double click does nothing. The same thing happen when I click
Open Recent or content...etc.

It seems the emulators' UI respond to "taps" and not "mouse clicks".

**Comment by Rakashazi** [comment] 2021-12-30 11:27
Thanks for reporting, I fixed the mouse click issue and also added basic support for the scroll wheel, will be included in 1.5.57.

**Closed by Rakashazi** 2021-12-30 11:27 UTC

**Comment by RebelliousX** [comment] 2021-12-31 18:07
Thanks a lot! That was quick. But it seems now RIGHT click exits the emulator to home screen instead of bringing the options window or a warning to confirm the exit.

**Comment by Rakashazi** [comment] 2022-01-01 11:06
Give the new build a try and see the right-click issue is fixed. About the crash when deleting saved device setting, I think I found the cause and will fix it in the next commit.

**Comment by RebelliousX** [comment] 2022-01-10 04:52
Thank you again for the hard work. And yes, the issue is fixed. I apologize for not describing the issue correctly,  it was not the right click, but the back button that was causing the issue. 👍🏻
