### ISSUE TITLE
Disable default 16 lines crop on top and bottom (NES.emu)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [Rakashazi/emu-ex-plus-alpha#87] opened 2016-12-21 07:46 UTC
current version of NES.emu crops first 8 lines on top and last 8 lines on bottom (see drawing area).
So, first line =8, last line =231 instead of first line =0, last line =239.

It appears both for NTSC and PAL modes.

Can you remove crop for draw full area? Or you can make option for remove crop.
Not sure for NTSC, but PAL/Dendy needs to draw full area.

![2](https://cloud.githubusercontent.com/assets/13199529/21380990/d0e01b6a-c769-11e6-906f-e7d326617d92.png)

Thank you

**Comment by M-a-r-k** [comment] 2020-01-14 21:29
This is probably a duplicate of issue #15.

**Comment by Rakashazi** [comment] 2022-02-12 07:45
An option for showing the overscan lines was added in the last commit.

**Closed by Rakashazi** 2022-02-12 07:45 UTC
